# Generated by Django 3.1.4 on 2020-12-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20201226_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='subscribed_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
