# Generated by Django 3.1.4 on 2020-12-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_users_subscribed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='subscribed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
